In [39]:
# import numpy as nm
# myarr =nm.array([[3,128,5,3]],nm.int16)
# myarr[0,1]
# myarr.shape
# myarr.dtype
# # **Conversion from other python structures**
# arr1=nm.array([[1,2,3],[4,5,6],[7,8,9]])
# arr1
# arr1.shape

# arr1.dtype
# arr1.size
# # **intrinsic numpy array objects**
# arr2 = nm.zeros((2,5))
# arr2
# arr3 = nm.arange(25)
# arr3
# arr4 = nm.linspace(0,7,4)
# arr4
# arr5 =nm.empty((4,6))
# arr5
# arr6 = nm.empty_like(arr1)
# arr6
# arr7 = nm.identity(4)
# arr7
# arr8 = nm.arange(45)
# arr8 =arr8.reshape(3,15)
# arr8.ravel()


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44])

**axis**

In [40]:
import numpy as np

In [46]:
myarr = np.arange(9)
myarr = myarr.reshape(3, 3)
myarr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [45]:
myarr.sum(axis=0)

array([ 9, 12, 15])

In [48]:
myarr.sum(axis=1)

array([ 3, 12, 21])

In [49]:
myarr.T

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [52]:
myarr.flat
for item in myarr.flat:
    print(item)

0
1
2
3
4
5
6
7
8


In [53]:
myarr.ndim

2

In [54]:
myarr.size

9

In [55]:
myarr.nbytes

36

In [56]:
one =np.array([1,2,3,4,5,6,7,8,9])

In [57]:
one.argmax()

8

In [61]:
one.argmin()

0

In [62]:
one.argsort()

array([0, 1, 2, 3, 4, 5, 6, 7, 8], dtype=int64)

In [63]:
myarr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [65]:
myarr.argmax()

8

In [66]:
myarr.argmin()

0

In [67]:
myarr.argmax(axis=0)

array([2, 2, 2], dtype=int64)

In [68]:
myarr.argmin(axis=0)

array([0, 0, 0], dtype=int64)

In [69]:
myarr.argsort(axis=0)

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2]], dtype=int64)

In [72]:
myarr2 = np.arange(9,18)
myarr2 = myarr2.reshape(3,3)

In [73]:
myarr2

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [74]:
myarr + myarr2

array([[ 9, 11, 13],
       [15, 17, 19],
       [21, 23, 25]])

In [75]:
myarr * myarr2

array([[  0,  10,  22],
       [ 36,  52,  70],
       [ 90, 112, 136]])

In [76]:
np.sqrt(myarr)

array([[0.        , 1.        , 1.41421356],
       [1.73205081, 2.        , 2.23606798],
       [2.44948974, 2.64575131, 2.82842712]])

In [77]:
myarr.sum()

36

In [84]:
np.where(myarr>6)

(array([2, 2], dtype=int64), array([1, 2], dtype=int64))

In [81]:
myarr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [85]:
np.count_nonzero(myarr)

8

In [88]:
import sys
py_ar = [1,2,3,4,5,6]
np_ar = np.array(py_ar)

In [90]:
sys.getsizeof(1) * len(py_ar)

168

In [91]:
np_ar.itemsize * np_ar.size

24